### ISSUE TITLE
Use names rather than identifiers everywhere

### ISSUE THREAD

**Issue by Jlobblet** [lifearoundfreaks/barotrauma-calc#2]
barotrauma-calc currently uses the identifier for several fields in the item box
![image](https://user-images.githubusercontent.com/37539527/104469999-154ef300-55b1-11eb-86dc-cb0c7cfe881e.png)
These fields' English localisations could be retrieved from the EnglishVanilla.xml file.
The proposed change would look like:
![image](https://user-images.githubusercontent.com/37539527/104470378-8f7f7780-55b1-11eb-9221-e0f90f6b1e08.png)
(although probably with the column appropriately resized)

**Comment by lifearoundfreaks** [comment]
> These fields' English localisations could be retrieved from the EnglishVanilla.xml file.

Eh, seemed kind of an overkill to change data structure and parsing logic to accommodate a few strings. Added those strings as a global const for now.

Thanks, the live version should already be updated.
