### ISSUE TITLE
base crafting skill level misleading for campaign

### ISSUE THREAD

**Issue by Tsunder** [lifearoundfreaks/barotrauma-calc#3]
- assuming base skill level of 15 is really low for campaign, and would then use the "skill too low to craft" multiplier for many many items

i think it's be better to assume the user has sufficient craft skill unless otherwise mentioned, so
suggest default craft skill of 100, or ignore the craft skill multiplier unless explicitly written

**Comment by lifearoundfreaks** [comment]
I thought this over and you are probably right.
