### ISSUE TITLE
add base price departure and destination options

### ISSUE THREAD

**Issue by Tsunder** [lifearoundfreaks/barotrauma-calc#4]
add "base price" (no multipliers) for departure and destination options
- items can be obtained from other sources like wrecks, which obviously don't have buy price.
- sometimes you just want to make the "most" profitable item to hold onto and sell at the right time, rather than to a specific place?
-- building on that, how about a "max sell" for destination and "minimum price" for departure, for maximum min-max planning? :D

**Comment by lifearoundfreaks** [comment]
Added all three. Whenever any of the new options is selected as a departure outpost, calculation logic assumes it is possible to buy at that price, even if it is not.

May expand this logic later if required.
