### ISSUE TITLE
display price multipliers for selected item

### ISSUE THREAD

**Issue by Tsunder** [lifearoundfreaks/barotrauma-calc#5]
when bringing up the detailed information on an item, it'd be nice to be able to compare its sell multipliers/price between the rest of the places it can be bought/sold from.

**Comment by lifearoundfreaks** [comment]
Would appreciate it if you explained in more detail or even gave visual examples. Or do you just want me to include those multipliers in the item info table?

**Comment by Tsunder** [comment]
currently to see the buy/sell price of an item, one would go to the wiki, or click on every permutation.

pretty much like the price table here:
https://barotraumagame.com/wiki/Underwater_Scooter
shows buys/sell price on each place.

Additionally, a little visual indicator of lowest/highest prices would be nice
